# Generated by Django 2.2.3 on 2019-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_auto_20190728_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='chip_number',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='st_number',
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscribers', to='newsletter.Category', verbose_name='Категории'),
        ),
    ]
