# Generated by Django 2.2.3 on 2019-07-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20190728_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='newsletter.Category', verbose_name='Категории'),
        ),
    ]
