# Generated by Django 2.2.3 on 2019-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0009_auto_20190728_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Не выбрано', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(related_name='subscribers', to='newsletter.Category', verbose_name='Категории'),
        ),
    ]
