# Generated by Django 2.2.3 on 2019-07-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0010_auto_20190728_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='category',
            field=models.ManyToManyField(blank=True, to='newsletter.Category', verbose_name='Категории'),
        ),
    ]
