# Generated by Django 2.2.3 on 2019-07-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0011_auto_20190728_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='gender',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=50, verbose_name='Пол'),
        ),
    ]
