# Generated by Django 2.2.3 on 2019-07-30 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0012_auto_20190728_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
