# Generated by Django 2.2.3 on 2019-07-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0013_auto_20190730_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='email',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscriber',
            field=models.ManyToManyField(to='newsletter.Subscriber'),
        ),
        migrations.DeleteModel(
            name='NewsLetterUser',
        ),
    ]
