# Generated by Django 2.2.3 on 2019-08-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0016_auto_20190730_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='birth_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
