# Generated by Django 2.2.3 on 2019-08-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0017_auto_20190802_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='pay_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
