# Generated by Django 2.2.3 on 2019-07-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriber_Excel',
            new_name='SubscriberExcel',
        ),
    ]
